### PR TITLE
first rough sketch of terra (game-engine api)

### PR DESCRIPTION
**Pull request by vasanthaganeshk**
just a rough sketch, lets discuss more!

### CODE REVIEW

**Comment by vasanthaganeshk** [comment]
I've updated the terra.md and sky.md

**Review by oyeb — CHANGES_REQUESTED** [review]
I need to see function calls too. Why stick to JSON? All that depends on the game implementation. Engine shouldn't care about the format of objects that are transferred to and from `bot` and `game`.

**Comment by oyeb** [comment]
Could you give me access to `vasanthaganesh:terra-design` as described [here](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/#enabling-repository-maintainer-permissions-on-existing-pull-requests)?
I'll be able to add commits to this PR after that.

**Comment by oyeb** [comment]
Next time, before sending a PR, you open a topic branch **from** `arrow-/phoenix:development` called `arrow-/phoenix:topic-branch`.
Don't send PRs to `master` or `development`, I will close them.
Then send a PR to it. Then everyone can add commits to the PR, not just me n you.

**Pull request merged**
